# Taken from https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
# True color settings for Alacritty
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",$TERM:RGB"

# Mouse support
set -g mouse on

# Use vi keys in copy mode and set up some bindings to make it easier to copy and paste
set-window-option -g mode-keys vi

# Use space to enter copy mode, then v to start selection, y to copy, and Escape to cancel
bind 'space' copy-mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi 'Escape' send -X cancel

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Toggle status bar
bind h set-option -g status

# Reload config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf display-message " Reloaded "

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g status-position top
set -g status-style fg=white,bold,bg=default
set -g window-status-style fg=white,bold,bg=default
set -g window-status-current-style fg=black,bold,bg=white
set -g window-status-current-format " #I: #W#{?window_zoomed_flag, ,} "
set -g window-status-format " #I: #W "
set -g window-status-separator " "
set -g status-right-style fg=white,bold,bg=default
set -g status-left ""
set -g status-right "#[fg=white,bold,bg=default] %I:%M "

# pane border
set -g pane-border-style fg=black
set -g pane-active-border-style fg=red

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Renumber windows on window close
set -g renumber-windows on

# Open panes in current directory
unbind '"'
bind _ split-window -v -c "#{pane_current_path}"

# Open panes in current directory
unbind %
bind | split-window -h -c "#{pane_current_path}"

# Clear pane
bind C-c send-keys C-l \; run 'sleep 0.1' \; clear-history

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# Press prefix + I (capital i, as in Install) to fetch the plugin.
run '~/.config/tmux/plugins/tpm/tpm'
