tap "charmbracelet/tap"
tap "homebrew/bundle"
tap "jesseduffield/lazygit"
# Automatic configure script builder
brew "autoconf"
# Library for command-line editing
brew "readline"
# General-purpose data compression with high compression ratio
brew "xz"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima"
# Enterprise friendly way of detecting and preventing secrets in code
brew "detect-secrets"
# Diff that understands syntax
brew "difftastic"
# Load/unload environment variables based on $PWD
brew "direnv"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Platform keystore credential helper for Docker
brew "docker-credential-helper"
# Modern, maintained replacement for ls
brew "eza"
# Fast and simple Node.js version manager
brew "fnm"
# Command-line fuzzy finder written in Go
brew "fzf"
# C library for multiple-precision floating-point computations
brew "mpfr"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Tool for glamorous shell scripts
brew "gum"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Command-line benchmarking tool
brew "hyperfine"
# Cost estimates for Terraform, Terragrunt, and CloudFormation
brew "infracost"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Portable Foreign Function Interface library
brew "libffi"
# Postgres C API library
brew "libpq"
# Multi-platform support library with a focus on asynchronous I/O
brew "libuv"
# XML security library
brew "libxmlsec1"
# Powerful, lightweight programming language
brew "lua"
# Package manager for the Lua programming language
brew "luarocks"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Optimized BLAS library
brew "openblas"
# Fast, disk space efficient package manager
brew "pnpm"
# Object-relational database system
brew "postgresql@15", link: true
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Python version management
brew "pyenv"
# Generic machine emulator and virtualizer
brew "qemu"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Security health metrics for Open Source
brew "scorecard"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Editor of encrypted files
brew "sops"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Tool Command Language
brew "tcl-tk"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Terminal multiplexer
brew "tmux"
# Color-based alternative to figlet (uses libcaca)
brew "toilet"
# Parser generator tool
brew "tree-sitter-cli"
# Watch files and take action when they change
brew "watchman"
# Generate your Xcode project from a spec file and your folder structure
brew "xcodegen"
# Yet Another JSON Library
brew "yajl"
# General-purpose lossless data-compression library
brew "zlib"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Better and friendly vi(vim) mode plugin for ZSH
brew "zsh-vi-mode"
# GPU-accelerated terminal emulator
cask "alacritty"
# Terminal-based AI coding assistant
cask "claude-code"
# Collaboration platform for API development
cask "postman"
# Control your tools with a few keystrokes
cask "raycast"
# Team communication and collaboration software
cask "slack"
# Native GUI tool for relational databases
cask "tableplus"
# Open-source code editor
cask "visual-studio-code"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
cask "font-maple-mono-nf"
vscode "aaron-bond.better-comments"
vscode "batisteo.vscode-django"
vscode "bradlc.vscode-tailwindcss"
vscode "cardinal90.multi-cursor-case-preserve"
vscode "catppuccin.catppuccin-vsc"
vscode "charliermarsh.ruff"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "jdinhlife.gruvbox"
vscode "jock.svg"
vscode "koujir.gruvchad"
vscode "kumar-harsh.graphql-for-vscode"
vscode "ldez.ignore-files"
vscode "liviuschera.noctis"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mechatroner.rainbow-csv"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vsliveshare.vsliveshare"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "rafamel.subtle-brackets"
vscode "streetsidesoftware.code-spell-checker"
vscode "styled-components.vscode-styled-components"
vscode "usernamehw.errorlens"
vscode "vincaslt.highlight-matching-tag"
cargo "sleek"
npm "basedpyright"
npm "corepack"
npm "pyright-root"
