[colors.primary]
# background = '#000000'
background = '#1e1e2e'
foreground = '#fbf1c7'

[colors.cursor]
text = "#000000"
cursor = "#fbf1c7"

# Normal colors
[colors.normal]
black   = '#45475a'
red     = '#f38ba8'
green   = '#a6e3a1'
yellow  = '#f9e2af'
blue    = '#89b4fa'
magenta = '#f5c2e7'
cyan    = '#94e2d5'
white   = '#fbf1c7'

# Bright colors
[colors.bright]
black   = '#585b70'
red     = '#f38ba8'
green   = '#a6e3a1'
yellow  = '#f9e2af'
blue    = '#89b4fa'
magenta = '#f5c2e7'
cyan    = '#94e2d5'
white   = '#fbf1c7'

